# Generated by Django 5.1.6 on 2025-02-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_address_user_blood_group_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='accesses',
            field=models.ManyToManyField(to='account.access'),
        ),
    ]
