# Generated by Django 5.1.6 on 2025-02-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_role_alter_teacherprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='core_subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='designation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(choices=[('IO', 'In Office'), ('OL', 'On Leave'), ('ON', 'Online')], default='IO', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2, null=True),
        ),
    ]
