# Generated by Django 5.1.6 on 2025-02-12 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_teacherprofile_core_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='salary',
        ),
    ]
