# Generated by Django 5.1.6 on 2025-02-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
