# Generated by Django 5.1.6 on 2025-02-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_caste_user_religion_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='total_roll',
            field=models.IntegerField(null=True),
        ),
    ]
