# Generated by Django 5.1.6 on 2025-02-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_studentprofile_total_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='accesses',
            field=models.ManyToManyField(blank=True, null=True, to='account.access'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('TE', 'Teacher'), ('ST', 'Student'), ('AD', 'Admin')], default='ST', max_length=5),
        ),
    ]
