# Generated by Django 5.1.6 on 2025-02-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_role_accesses_alter_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='section',
        ),
        migrations.AlterField(
            model_name='role',
            name='accesses',
            field=models.ManyToManyField(blank=True, to='account.access'),
        ),
    ]
