# Generated by Django 5.1.6 on 2025-02-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_teacherprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
    ]
