# Generated by Django 5.1.6 on 2025-02-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_attendance'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fees',
            options={'verbose_name': 'Fees', 'verbose_name_plural': 'Fees'},
        ),
        migrations.AlterUniqueTogether(
            name='fees',
            unique_together={('type', 'grade')},
        ),
    ]
