# Generated by Django 5.1.6 on 2025-02-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_section_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='max_student',
            field=models.IntegerField(null=True),
        ),
    ]
