# Generated by Django 5.1.6 on 2025-02-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_section_max_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='max_student',
            field=models.IntegerField(default=40),
        ),
    ]
