# Generated by Django 5.1.6 on 2025-02-16 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('', '---'), ('MN', 'Monday'), ('TU', 'Tuesday'), ('WD', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday')], max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='period',
            field=models.CharField(choices=[('', '---'), ('1', '1st Period'), ('2', '2nd Period'), ('3', '3rd Period'), ('4', '4th Period'), ('5', '5th Period'), ('6', '6th Period')], max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('day', 'period', 'teacher')},
        ),
    ]
