# Generated by Django 5.1.6 on 2025-02-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_schedule_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('', '---'), ('1MN', 'Monday'), ('2TU', 'Tuesday'), ('3WD', 'Wednesday'), ('4TH', 'Thursday'), ('5FR', 'Friday')], max_length=5),
        ),
    ]
